server:
  port: 8080
spring:
  application:
    name: oauth2-client
  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: on
    cors:
      allowed-origin-patterns: "*"
      allowed-headers: "*"
      allowed-methods: "*"

  security:
    oauth2:
      client:
        registration:
          okta:
            scope:
              - openid
              - email
            #client-id:
            #client-secret:
        provider:
          okta:
            issuer-uri: https://dev-2322327.okta.com
      resourceserver:
        opaquetoken:
          introspection-uri: https://dev-2322327.okta.com/oauth2/v1/introspect
          #client-id:
          #client-secret:

logging:
  level:
    root: debug
