server:
  port: 8080
spring:
  application:
    name: oauth2-client
  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: on
    cors:
      allowed-origin-patterns: "*"
      allowed-headers: "*"
      allowed-methods: "*"

  security:
    oauth2:
      client:
        registration:
          okta:
            scope:
              - openid
              - email
              #            client-id:
              #            client-secret:
              #redirect-uri: http://localhost:8080/login/oauth2/code/
        provider:
          okta:
            issuer-uri: https://dev-2322327.okta.com
      resourceserver:
        jwt:
          issuer-uri: https://dev-2322327.okta.com
logging:
  level:
    root: debug
