server:
  port: 8080
#  forward-headers-strategy: framework
spring:
  application:
    name: Spring Cloud Gateway w/ OIDC Example
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      #        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      #      globalcors:
      #        cors-configurations:
      #          '[/**]':
      #            allowed-origins:
      #              - "http://localhost:4200"
      #              - "http://localhost:4200/"
      #            allowed-methods:
      #              - "*"
      #            allowed-headers:
      #              - "*"
      #        #              - "authorization"
      #        #              - "content-type"
      #        add-to-simple-url-handler-mapping: true
      routes:
        - id: graphql_route
          uri: http://localhost:8081
          predicates:
            - Path=/graphql/**
        - id: graphiql_route
          uri: http://localhost:8081
          predicates:
            - Path=/graphiql/**
        - id: name_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/{path}/**
          filters:
            - RewritePath=/api/(?<segment>.+), /$\{segment}

logging:
  level:
    org.springframework: debug
    org.springframework.cloud.gateway: trace
