spring:
  application:
    name: ignite-example
  boot:
    admin:
      client:
        url: http://127.0.0.1:8081
  kafka:
    bootstrap-servers: localhost:9092
    client-id: my-client-id
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      group-id: my-group-id
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    de.codecentric.boot.admin: debug
    #    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: debug
    org.apache.ignite.internal.managers.eventstorage.GridEventStorageManager: debug
#    org.apache.kafka: debug
#    org.springboot.kafka: debug
